version: '3.9'

services:
  db:
    container_name: 2FA-db
    restart: unless-stopped
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

